import {LivingTree} from './LivingTree.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {Sun,Target,CalendarBlank,Plant,Gear,Sparkle,Plus,ArrowLeft,ArrowRight,Check,X,Clock,ArrowsOutSimple,DotsThree,ArrowCounterClockwise,Leaf,Warning,Eye,CaretRight,CaretDown,CheckCircle,BookOpen,ArrowSquareOut,Pause,Play,Trash,Info,Buildings,Planet,ArrowDown,Lightning} from '@phosphor-icons/react';
import {MODES,growthFor,daysBetween,TODAY} from '../domain/model.js';
const icons={today:Sun,goals:Target,calendar:CalendarBlank,growth:Plant,settings:Gear,spark:Sparkle,plus:Plus,left:ArrowLeft,right:ArrowRight,check:Check,close:X,clock:Clock,expand:ArrowsOutSimple,more:DotsThree,undo:ArrowCounterClockwise,leaf:Leaf,warning:Warning,eye:Eye,chevron:CaretRight,down:CaretDown,done:CheckCircle,book:BookOpen,external:ArrowSquareOut,pause:Pause,play:Play,trash:Trash,info:Info,city:Buildings,planet:Planet,arrowdown:ArrowDown,lightning:Lightning};
export function Icon({name,size=20,...props}){const C=icons[name]||Plant;return <C size={size} weight="regular" aria-hidden="true" {...props}/>}
export function Button({children,icon,variant='',...props}){return <button className={`button ${variant}`} {...props}>{icon&&<Icon name={icon} size={17}/>} {children}</button>}
export function Modal({title,children,onClose,wide=false}){const ref=useRef();useEffect(()=>{const el=ref.current;const previous=document.activeElement;el.showModal();return()=>{el.close();previous?.focus()}},[]);return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}} aria-labelledby="modal-title"><div className="modal-head"><h2 id="modal-title">{title}</h2><button className="icon-button" aria-label="关闭" onClick={onClose}><Icon name="close"/></button></div>{children}</dialog>}
export function Empty({title,children}){return <div className="empty"><Icon name="leaf" size={30}/><h3>{title}</h3><p>{children}</p></div>}
export function GrowthScene({goal,state,compact=false,feedback=false}){
 const mode=MODES[goal.growthModeId],growth=growthFor(state,goal.id),[failed,setFailed]=useState(false);
 const stage=growth===0?'等待萌芽':growth<5?'新叶初生':growth<15?'舒展枝叶':'枝叶渐丰';
 const changeText=goal.growthModeId==='tree'?(growth%5===0&&growth>0?'新叶间，开出了一朵小花。':'树枝上，多了一对新叶。'):goal.growthModeId==='city'?'城市里，又亮起了一盏灯。':'星球上，多了一点生命的光。';
 useEffect(()=>setFailed(false),[mode.asset]);
 return <div className={`growth-scene ${goal.growthModeId} ${compact?'compact':''} ${feedback?'growing':''}`}>
 {goal.growthModeId==='tree'&&!compact?<LivingTree growth={growth} feedback={feedback}/>:!failed?<img src={`/assets/${mode.asset}`} alt={`${mode.name}：${stage}`} onError={()=>setFailed(true)} style={{transform:`scale(${1+Math.min(growth,100)*.0014})`}}/>:<div className="scene-fallback"><Icon name="leaf" size={44}/><span>场景暂未加载，成长记录仍然保留</span></div>}
 {!compact&&<><div className="scene-copy"><span className="eyebrow">{mode.en} <span className="tiny-dot"/> DAY {Math.max(1,daysBetween(goal.startDate,TODAY)+1)}</span><h2>{goal.title}</h2><p className="growth-stage">{goal.growthModeId==='tree'?stage:mode.stage}<span>／</span>{mode.name}</p><p className="growth-message">{growth===0?'从一颗种子开始，让行动留下痕迹。':'不必急着长成，每一份投入都算数。'}</p><div className="scene-caption"><Icon name="leaf" size={16}/><span role={feedback?'status':undefined}>{feedback?changeText:growth===0?'完成第一项任务，让世界开始成长':`已积累 ${growth} 份行动 · ${goal.growthModeId==='tree'?`${growth*2} 片新叶`:'持续生长中'}`}</span></div></div><div className="world-stamp"><span>你的世界正在生长</span><b>{String(growth).padStart(2,'0')}<small>份行动</small></b></div>{goal.growthModeId!=='tree'&&growth>=5&&<div className="milestone-blooms" aria-label={`已达成 ${Math.floor(growth/5)} 个演示里程碑`}>{Array.from({length:Math.min(12,Math.floor(growth/5))},(_,i)=><span key={i} style={{left:`${62+i*11%29}%`,top:`${30+i*17%40}%`}}><Icon name="spark" size={18}/></span>)}</div>}{goal.growthModeId!=='tree'&&<div className="growth-particles" aria-hidden="true">{Array.from({length:Math.min(growth,24)},(_,i)=><span key={i} style={{left:`${58+(i*17%32)}%`,top:`${22+(i*13%48)}%`,animationDelay:`${i*.12}s`}}><Icon name={goal.growthModeId==='tree'?'leaf':goal.growthModeId==='city'?'lightning':'spark'} size={9+i%3*2}/></span>)}</div>}</>}
 </div>
}
export function Steps({current}){return <div className="steps">{['定义目标','研究与世界','审核计划','安排今天'].map((s,i)=><React.Fragment key={s}><span className={i===current?'current':i<current?'finished':''}><b>{i<current?<Icon name="check" size={13}/>:i+1}</b>{s}</span>{i<3&&<i/>}</React.Fragment>)}</div>}
