import React,{useState,useEffect,useRef} from 'react';
import {TODAY,MODES,seed,makeGoal,createPlan,generateWeekTasks,setCompletion,scheduleTask,conflicts,growthFor,addDays,shortDate,timeLabel,timeValue,updateMonth,updateWeek} from './domain/model.js';
import {Icon,Button,Modal,Empty,GrowthScene,Steps} from './components/Shared.jsx';
import {CreateGoal,Research,PlanReview} from './components/Planning.jsx';
import {Today} from './components/Today.jsx';
const KEY='mingrifu-v3-demo-1';
function load(){try{const v=JSON.parse(sessionStorage.getItem(KEY));if(v?.goals?.length&&v.tasks&&v.events)return v}catch{}return seed()}
export function App(){
 const [state,setState]=useState(load),[page,setPage]=useState('today'),[activeId,setActiveId]=useState('exam'),[date,setDate]=useState(TODAY),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[feedback,setFeedback]=useState(null),[focus,setFocus]=useState(false),[reduce,setReduce]=useState(false);
 const [draft,setDraft]=useState(()=>{try{const saved=JSON.parse(sessionStorage.getItem(KEY+'-draft'));if(saved&&typeof saved.title==='string')return saved}catch{}return {title:'',description:'',startDate:TODAY,targetDate:'2027-09-18',timeBudget:5,foundation:'',notes:''}});
 useEffect(()=>{try{sessionStorage.setItem(KEY+'-draft',JSON.stringify(draft))}catch{}},[draft]);
 const goal=state.goals.find(g=>g.id===activeId)||state.goals[0];
 useEffect(()=>{try{sessionStorage.setItem(KEY,JSON.stringify(state))}catch{}},[state]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>{if(!feedback)return;const t=setTimeout(()=>setFeedback(null),1800);return()=>clearTimeout(t)},[feedback]);
 const notify=message=>setToast(message);
 const updateGoal=(id,fn)=>setState(s=>({...s,goals:s.goals.map(g=>g.id===id?fn(g):g)}));
 const nav=(p)=>{setModal(null);setPage(p);window.scrollTo({top:0,behavior:'instant'})};
 const startResearch=(input)=>{const g=makeGoal(input);g.research={step:0,status:'researching',sources:[]};setState(s=>({...s,goals:[...s.goals,g]}));setActiveId(g.id);nav('research')};
 const complete=(id,done)=>{const t=state.tasks.find(t=>t.id===id);setState(s=>setCompletion(s,id,done));if(done){setActiveId(t.goalId);setFeedback(t.goalId);const n=growthFor(state,t.goalId)+1;notify(n%5===0?'新的里程碑：又完成了五份行动，世界多了一点生机。':'已完成。你的世界又生长了一点。')}else notify('已撤销完成，对应的成长也已回退。')};
 const schedule=(id,start,duration)=>{try{scheduleTask(state,id,start,duration);setState(s=>scheduleTask(s,id,start,duration));return true}catch(e){notify(e.message);return false}};
 return <div className={`app ${reduce?'reduce-motion':''} ${modal?.type==='task'?'has-task-panel':''}`}>
 <aside className="sidebar"><a href="#today" className="brand" onClick={e=>{e.preventDefault();nav('today')}}><span className="brand-mark"><Icon name="leaf" size={27}/></span><span>明日复<small>MAKE TOMORROW GROW</small></span></a><div className="workspace-label">我的空间 <span>个人</span></div><nav aria-label="主导航">{[['today','今日'],['goals','目标'],['calendar','日历'],['growth','成长']].map(([id,label])=><button key={id} className={page===id||id==='goals'&&['create','research','plan'].includes(page)?'nav-item active':'nav-item'} onClick={()=>nav(id)}><Icon name={id}/>{label}{id==='today'&&<small>{state.tasks.filter(t=>t.date===date&&t.executionStatus!=='completed').length}</small>}</button>)}</nav><div className="sidebar-divider"/><div className="workspace-label">正在生长 <button aria-label="创建目标" className="icon-button" onClick={()=>nav('create')}><Icon name="plus" size={15}/></button></div><div className="goal-links">{state.goals.filter(g=>g.status==='active').map(g=><button key={g.id} onClick={()=>{setActiveId(g.id);nav('today')}} className={g.id===activeId?'selected':''}><span className={`goal-dot ${g.growthModeId}`}/>{g.title}</button>)}</div><div className="sidebar-bottom"><div className="quiet-note"><Icon name="leaf" size={23}/><p>不必急着成为大树。<br/>今天，先长出一片叶子。</p></div><button className="nav-item" onClick={()=>nav('settings')}><Icon name="settings"/>设置</button><div className="profile"><span>弈</span><div>我的明日<small>慢慢来，也在向前</small></div><span className="online"/></div></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumb">我的空间 <Icon name="chevron" size={13}/> <span>{{today:'今日',goals:'目标',calendar:'日历',growth:'成长',settings:'设置',create:'创建目标',research:'目标研究',plan:'审核计划'}[page]}</span></div><div className="top-actions"><span className="demo-label"><span/>演示模式</span><button className="avatar" aria-label="个人设置" onClick={()=>nav('settings')}>弈</button></div></header>
 <main>
 {page==='today'&&<Today {...{state,goal,date,setDate,complete,schedule,focus,setFocus,feedback}} onGoal={setActiveId} onCreate={()=>nav('create')} onTask={t=>setModal({type:'task',taskId:t.id})} onPlan={()=>nav('plan')}/>}
 {page==='create'&&<CreateGoal draft={draft} setDraft={setDraft} onStart={startResearch} onBack={()=>nav('goals')}/>}
 {page==='research'&&<Research goal={goal} updateGoal={updateGoal} onNext={()=>nav('plan')}/>}
 {page==='plan'&&<PlanReview goal={goal} state={state} updateGoal={updateGoal} setState={setState} notify={notify} onNext={d=>{setDate(d);nav('today')}} onBack={()=>nav('research')}/>}
 {page==='goals'&&<><div className="page-heading"><div><span className="eyebrow">A LITTLE CLOSER, EVERY DAY</span><h1>每一个目标，都有自己的世界。</h1><p>把期待变成计划，让行动留下痕迹。</p></div><Button variant="primary" icon="plus" onClick={()=>nav('create')}>创建新目标</Button></div><div className="goal-grid">{state.goals.map(g=><article className="goal-card" key={g.id}><GrowthScene goal={g} state={state} compact/><div className="goal-card-content"><span className="eyebrow">{MODES[g.growthModeId].en}</span><h2>{g.title}</h2><p>{shortDate(g.startDate)} — {shortDate(g.targetDate)} · {g.status==='draft'?'待确认计划':`${growthFor(state,g.id)} 份行动`}</p><Button icon="right" onClick={()=>{setActiveId(g.id);nav(g.months.length?'plan':'research');if(!g.months.length)updateGoal(g.id,x=>({...x,research:{...x.research,status:'researching'}}))}}>{g.months.length?'查看与编辑计划':'继续创建'}</Button></div></article>)}</div></>}
 {page==='growth'&&<><div className="page-heading"><div><span className="eyebrow">YOUR LIVING WORLDS</span><h1>成长，是行动留下的回声。</h1><p>每个世界只由它所属目标的行动推动。</p></div></div><div className="world-tabs">{state.goals.map(g=><button key={g.id} className={goal.id===g.id?'active':''} onClick={()=>setActiveId(g.id)}>{g.title}</button>)}</div><GrowthScene goal={goal} state={state}/><div className="section-title"><h2>这次旅程的足迹</h2><span>本次演示完成记录</span></div>{state.events.filter(e=>e.goalId===goal.id).length?state.events.filter(e=>e.goalId===goal.id).map(e=><div className="history-row" key={e.id}><Icon name="leaf"/><div><b>{state.tasks.find(t=>t.id===e.taskInstanceId)?.title}</b><p>一次行动，一点新的生长</p></div><span>{new Date(e.occurredAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</span></div>):<Empty title="第一片新的叶子，等你种下">完成一项任务后，这里会留下成长的足迹。完整历史将在后续版本扩展。</Empty>}</>}
 {page==='calendar'&&<><div className="page-heading"><div><span className="eyebrow">ONE DAY AT A TIME</span><h1>给未来，留一点空间。</h1><p>跨日视图将在后续完善。现在可以选择日期，安排同一份任务清单。</p></div></div><section className="simple-panel"><label>选择日期<input type="date" value={date} onChange={e=>setDate(e.target.value||TODAY)}/></label><Button variant="primary" icon="right" onClick={()=>nav('today')}>查看这一天</Button></section></>}
 {page==='settings'&&<><div className="page-heading"><div><span className="eyebrow">MAKE IT YOURS</span><h1>保持适合自己的节奏。</h1><p>本轮为交互原型，不连接真实 AI，也不收集密钥。</p></div></div><section className="settings-panel"><h2>体验偏好</h2><label className="switch-row"><span><b>减少动态效果</b><small>用静态变化保留每一份成长反馈</small></span><input type="checkbox" checked={reduce} onChange={e=>setReduce(e.target.checked)}/></label><div className="setting-row"><span>演示日期与时区</span><b>2026 年 9 月 19 日 · Asia/Shanghai</b></div><h2>AI 服务</h2><div className="notice"><Icon name="info"/>未配置 · 正式版本将支持自带密钥（BYOK）</div><p>当前研究、来源与计划均为模拟数据。草稿与操作仅保留在当前浏览器标签页会话中。演示规则：每项任务完成计入一份行动，撤销即回退；每五份行动显示里程碑。场景初始行动数为预置示例，非真实历史。</p><Button variant="danger" onClick={()=>setModal({type:'reset'})}>重置演示数据</Button></section></>}
 </main><footer className="app-footer">明日复 <span>让每一天的努力，都看得见。</span><span>3.0 · 交互原型</span></footer></div>
 {toast&&<div className="toast" role="status"><Icon name="check" size={18}/>{toast}<button aria-label="关闭提示" onClick={()=>setToast('')}><Icon name="close" size={15}/></button></div>}
 {modal?.type==='task'&&<TaskDialog key={modal.taskId} task={state.tasks.find(t=>t.id===modal.taskId)} state={state} onClose={()=>setModal(null)} onSave={(id,start,duration)=>{if(schedule(id,start,duration)){setModal(null);notify(start===null?'已移回待安排，任务仍然保留。':'时间已安排。重叠时段会显示冲突提醒。')}}} onComplete={complete} onStatus={(id,status)=>setState(s=>({...s,tasks:s.tasks.map(t=>t.id===id?{...t,executionStatus:status}:t)}))}/>}
 {modal?.type==='reset'&&<Modal title="重新开始这次演示？" onClose={()=>setModal(null)}><p>将清除当前标签页中创建的目标、编辑和任务完成记录，恢复示例数据。</p><div className="modal-actions"><Button onClick={()=>setModal(null)}>取消</Button><Button variant="primary" onClick={()=>{setState(seed());setActiveId('exam');setDate(TODAY);setModal(null);nav('today');notify('已恢复演示数据')}}>确认重置</Button></div></Modal>}
 </div>
}
function TaskDialog({task,state,onClose,onSave,onComplete,onStatus}){
 const [error,setError]=useState('');
 const [start,setStart]=useState(task.scheduledStart===null?'09:00':timeLabel(task.scheduledStart)),[duration,setDuration]=useState(task.estimatedDuration);const g=state.goals.find(g=>g.id===task.goalId);
 return <TaskPanel onClose={onClose}><span className="tag">{g?.title}</span><h3 className="task-dialog-title">{task.title}</h3><p>{task.description}</p>{task.needsReview&&<div className="notice">所属计划已经修改，请核对这项任务是否仍适合。</div>}<form onSubmit={e=>{e.preventDefault();const minutes=timeValue(start),length=Number(duration);if(!Number.isFinite(minutes)||!Number.isFinite(length)||length<15||minutes+length>1440){setError('时间需在同一天内，时长至少 15 分钟。');return}setError('');onSave(task.id,minutes,length)}}><div className="form-row"><label>开始时间<input required type="time" step="900" value={start} onInput={e=>setStart(e.currentTarget.value)} onChange={e=>setStart(e.target.value)}/></label><label>持续时间（分钟）<input required type="number" min="15" max="1440" step="5" value={duration} onChange={e=>setDuration(e.target.value)}/></label></div>{error&&<div className="error" role="alert">{error}</div>}<p className="muted">{shortDate(task.date)} · 可直接完成未排程任务</p><div className="modal-actions"><Button type="button" onClick={()=>{onComplete(task.id,task.executionStatus!=='completed');onClose()}} icon={task.executionStatus==='completed'?'undo':'check'}>{task.executionStatus==='completed'?'撤销完成':'完成任务'}</Button><Button variant="primary" type="submit">保存时间</Button></div><div className="secondary-actions">{task.scheduledStart!==null&&<button type="button" onClick={()=>onSave(task.id,null,Number(duration))}>移回待安排</button>}{task.executionStatus!=='completed'&&<button type="button" onClick={()=>{onStatus(task.id,task.executionStatus==='in_progress'?'pending':'in_progress');onClose()}}>{task.executionStatus==='in_progress'?'暂停执行':'开始执行'}</button>}</div></form></TaskPanel>
}

function TaskPanel({children,onClose}){
 const ref=useRef();
 useEffect(()=>{const previous=document.activeElement;ref.current?.focus();return()=>previous?.isConnected&&previous.focus()},[]);
 return <aside ref={ref} tabIndex={-1} className="task-panel" role="dialog" aria-label="行动详情" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose()}}}>
 <div className="modal-head"><h2>行动详情</h2><button className="icon-button" aria-label="关闭行动详情" onClick={onClose}><Icon name="close"/></button></div>{children}
 </aside>
}
